---
- hosts: dockers
  vars:
    user: "gitstarinc"
    repo: "nodegit-http"
    git_dir: "/home/linode/"

  sudo: yes

  tasks:
  - name: make sure linode stuff is spooled up and running
    sudo: no
    local_action:
        module: linode
        api_key: '{{ linode_api_key }}'
        name: gitstar-docker
        linode_id: 729506
        state: started


  - name: make sure we have docker apt key
    apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

  - name: make sure we have docker apt repo
    apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

  - name: install docker
    apt: name=lxc-docker update_cache=yes state=latest

  - name: check if pip installed
    stat: path=/usr/local/bin/pip
    register: st

  - name: download pip (apt version has a bug breaking it hard)
    get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp mode=0740
    when: not st.stat.exists

  - name: installs pip
    command: /usr/bin/python /tmp/get-pip.py creates=/usr/local/bin/pip

  - name: install docker-py
    pip: name=docker-py state=latest

  - name: install ufw
    apt: name=ufw state=latest

  - name: change default forwarding rule
    lineinfile: dest=/etc/default/ufw regexp="^DEFAULT_FORWARD_POLICY=" line='DEFAULT_FORWARD_POLICY="ACCEPT"' state=present

  - name: allow ssh through firewall
    ufw: proto=tcp port=ssh rule=allow

  - name: rate limit on ssh
    ufw: rule=limit port=ssh proto=tcp

  - name: allow docker traffic
    ufw: proto=tcp port=2375 rule=allow

  - name: disable all incoming traffic
    ufw: state=enabled direction=incoming policy=deny

- include: app_servers.yml
