---
- name: run nginx reverse proxy container
  docker:
    image: nginx:latest
    ports: 80:80, 443:443
    name: proxy
    state: running
    volumes:
      - /tmp/nginx.conf.d/:/etc/nginx/conf.d/:ro

- name: Allow nginx firewall
  ufw: proto=tcp port=80 rule=allow
- name: Allow nginx ssl firewall
  ufw: proto=tcp port=443 rule=allow
